start: function_definition
function_definition: signature block
signature: CNAME CNAME arguments
arguments: "(" variable_definition ("," variable_definition)* ")"

block: "{" expression (";" expression)* "}"
expression: if | operation | CNAME

if: "if" expression block "else" block

variable_definition: CNAME CNAME

operation: CNAME INFIX_OPERATOR CNAME
INFIX_OPERATOR: ">"

%import common.WS
%import common.CNAME
%ignore WS